const titles = [
    "Bones",
    "Broken Strings",
    "The Wilhelm Scream (feat. Meghgan Washington)",
    "The Man",
    "Funky Cold Medina",
    "Don't Stop Believin'",
    "Requiem Mass in D Minor, K. 626: III. Lacrimosa",
    "Boulevard of Broken Dreams",
    "California Gurls (feat. Snoop Dogg)",
    "Locomotive Breath",
    "Seen It All",
    "Touch The Sky (feat. Lupe Fiasco)",
    "Sensory Division",
    "Nuthin' but a G'thang",
    "Replay",
    "Look Alive (feat. Drake)",
    "The Pretender",
];

const artists = [
    "Imagine Dragons",
    "James Morrison",
    "The Bamboos",
    "The Killers",
    "Tone-Lōc",
    "Journey",
    "Mozart",
    "Green Day",
    "Katy Perry",
    "Jethro Tull",
    "Jake Bugg",
    "Kanye West (Ye)",
    "Dimension",
    "Snoop Doggy Dogg & Dr.Dre",
    "Iyaz",
    "BlocBoy JB",
    "Foo Fighters",
];

const images = [
    "Bones.webp",
    "Broken-Strings.jpg",
    "The-Wilhelm-Scream.jfif",
    "The-Man.jfif",
    "Funky-Cold-Medina.jpg",
    "Don't-Stop-Believin'.jpg",
    "Lacrimosa.png",
    "Boulevard-of-Broken-Dreams.jpg",
    "California-Gurls.jpg",
    "Locomotive-Breath.jpg",
    "Seen-It-All.jpg",
    "Touch-The-Sky.jpg",
    "Sensory-Division.jpg",
    "Nuthin'-but-a-G'thang.jpg",
    "Replay.webp",
    "Look-Alive.jpg",
    "The-Pretender.jpg",
];

const audios = [
    "Bones.mp3",
    "Broken-Strings.mp3",
    "The-Wilhelm-Scream.mp3",
    "The-Man.mp3",
    "Funky-Cold-Medina.mp3",
    "Don't-Stop-Believin'.mp3",
    "Lacrimosa.mp3",
    "Boulevard-of-Broken-Dreams.mp3",
    "California-Gurls.mp3",
    "Locomotive-Breath.mp3",
    "Seen-It-All.mp3",
    "Touch-The-Sky.mp3",
    "Sensory-Division.mp3",
    "Nuthin'-but-a-G'thang.mp3",
    "Replay.mp3",
    "Look-Alive.mp3",
    "The-Pretender.mp3",
];